channel_sources:
  - nsls2forge,defaults,conda-forge
channel_targets:
  - nsls2forge main
cdt_name:
  - cos6
c_compiler_version:            # [unix]
  - 7                          # [linux]
cxx_compiler_version:          # [unix]
  - 7                          # [linux]
numpy:
  - 1.16
python:
  - 3.7
python_impl:
  - cpython
